version: 2.1

orbs:
  codacy_plugins_test: codacy/plugins-test@0.7.0
  
jobs:
  unit_test:
    docker:  # run the steps with Docker
      - image: circleci/elixir:1.7.3
    working_directory: ~/codacy-credo
    steps:
      - checkout
      - run:
          name: Install Hex locally and fetch copy of rebar
          command: mix do local.hex --force, local.rebar --force
      - run:
          name: Get dependencies
          command: mix deps.get
      - run:
          name: Compile dependencies
          command: mix deps.compile
      - run:
          name: Run tools native tests
          command: mix test

  publish_local:
    machine: true
    working_directory: ~/workdir
    steps:
      - checkout
      - run: 
          name: Publish tool docker locally
          command: ./build.sh $CIRCLE_PROJECT_REPONAME latest
      - run:
          name: Save docker to file
          command: |
            docker save --output ~/workdir/docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir/docker-image.tar

  publish:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input ~/workdir/docker-image.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:2.0.$CIRCLE_BUILD_NUM
              docker push codacy/$CIRCLE_PROJECT_REPONAME
            fi
workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - unit_test
      - publish_local
      - codacy_plugins_test/run:
          name: plugins_test
          requires:
            - publish_local
      - publish:
          requires:
            - unit_test
            - publish_local
            - plugins_test
