version: 2.1

orbs:
  codacy: codacy/base@1.2.1
  codacy_plugins_test: codacy/plugins-test@0.7.0

jobs:
  unit_test:
    docker:  # run the steps with Docker
      - image: circleci/elixir:1.7.3
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install Hex locally and fetch copy of rebar
          command: mix do local.hex --force, local.rebar --force
      - run:
          name: Get dependencies
          command: mix deps.get
      - run:
          name: Compile dependencies
          command: mix deps.compile
      - run:
          name: Run tools native tests
          command: mix test

  publish_docker_local:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: Publish tool docker locally
          command: ./build.sh $CIRCLE_PROJECT_REPONAME latest
      - run:
          name: Save docker to file
          command: |
            docker save --output ~/workdir/docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir/docker-image.tar

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - unit_test:
          requires:
            - codacy/checkout_and_version
      - publish_docker_local:
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          requires:
            - publish_docker_local
      - codacy/shell:
          name: publish_dockerhub
          context: CodacyDocker
          cmd: |
            docker load --input ~/workdir/docker-image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
          requires:
            - plugins_test
            - unit_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_dockerhub
